
networks:
  default:
    name: ${NETWORK}
    external: true


services:
  cron:
    image: mcuadros/ofelia:latest
    restart: ${SRV_RESTART_MODE:-always}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    command: daemon --docker
    deploy:
      resources:
        limits:
          memory: ${RES_LIMIT_MEM_SUPERCRONIC:-128M}
        reservations:
          memory: ${RES_RESER_MEM_SUPERCRONIC:-64M}
  docker-cli:
    image: docker:24
    command: tail -f /dev/null
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.dockerps.schedule: "@every 50s"
      ofelia.job-exec.dockerps.command: "docker ps -a"