
networks:
  default:
    name: ${NETWORK}
    external: true


services:
  cron:
    image: mcuadros/ofelia:latest
    restart: ${SRV_RESTART_MODE:-always}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    command: daemon --docker
    labels:
      ofelia.enabled: "true"
      ofelia.job-local.my-test-job.schedule: "@every 5s"
      ofelia.job-local.my-test-job.command: "docker ps -a"
    deploy:
      resources:
        limits:
          memory: ${RES_LIMIT_MEM_SUPERCRONIC:-128M}
        reservations:
          memory: ${RES_RESER_MEM_SUPERCRONIC:-64M}