
networks:
  default:
    name: ${NETWORK}
    external: true


services:
  cron:
    image: mcuadros/ofelia:latest
    restart: ${SRV_RESTART_MODE:-always}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    command: daemon --docker
    labels:
      ofelia.enabled: "true"
      # 在 host docker 上运行命令
      ofelia.job-exec.list.schedule: "@every 5s"
      ofelia.job-exec.list.container: "cron"     # 随便指一个正在运行的容器
      ofelia.job-exec.list.command: "docker ps -a"
    deploy:
      resources:
        limits:
          memory: ${RES_LIMIT_MEM_SUPERCRONIC:-128M}
        reservations:
          memory: ${RES_RESER_MEM_SUPERCRONIC:-64M}