
# docker network create --driver overlay --attachable cluster
networks:
  default:
    name: ${NETWORK}
    external: true


services:

  phpadmin:
    image: phpmyadmin/phpmyadmin
    hostname: phpadmin
    # restart: ${SRV_RESTART_MODE:-always}
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - ${PORT_PHPADMIN}:80
    environment:
      - PMA_ARBITRARY=1
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.phpadmin-auth.basicauth.users=admin:${HTPASSWD}
      - traefik.http.routers.phpadmin.rule=Host(`phpadmin.${DOMAIN}`)
      - traefik.http.routers.phpadmin.tls=true
      - traefik.http.routers.phpadmin.middlewares=phpadmin-auth
      - traefik.http.routers.phpadmin.entrypoints=websecure
      - traefik.http.routers.phpadmin.service=phpadmin@docker
      - traefik.http.services.phpadmin.loadbalancer.server.port=80
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/index.php || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s
    deploy:
      restart_policy:
        condition: ${SRV_RESTART_MODE:-any}
      replicas: 1
      placement:
        constraints:
          - node.labels.app_phpadmin == true
      resources:
        limits:
          memory: ${RES_LIMIT_MEM_PHPADMIN:-512M}
        reservations:
          memory: ${RES_RESER_MEM_PHPADMIN:-128M}

