
# docker network create --driver overlay --attachable cluster
networks:
  default:
    name: ${NETWORK}
    external: true



services:
  drawio:
    image: jgraph/drawio
    restart: ${SRV_RESTART_MODE:-always}
    ports:
      - "${PORT_DRAWIO}:8080"
    environment:
      PUBLIC_DNS: drawio.${DOMAIN}
      ORGANISATION_UNIT: unit
      ORGANISATION: org
      CITY: city
      STATE: state
      COUNTRY_CODE: country
    labels:
      - traefik.enable=true
      - traefik.http.routers.drawio.rule=HostRegexp(`^drawio\..*`)
      - traefik.http.routers.drawio.tls=true
      - traefik.http.routers.drawio.entrypoints=websecure
      - traefik.http.routers.drawio.service=drawio@docker
      - traefik.http.services.drawio.loadbalancer.server.port=8080
      - traefik.http.services.drawio.loadBalancer.passHostHeader=true
    deploy:
      resources:
        limits:
          memory: ${RES_LIMIT_MEM_DRAWIO:-512M}
        reservations:
          memory: ${RES_RESER_MEM_DRAWIO:-128M}