


services:
  3x-ui:
    image: ghcr.io/xeefei/3x-ui:latest
    restart: ${SRV_RESTART_MODE:-always}
    network_mode: host
    environment:
      - XRAY_VMESS_AEAD_FORCED=false
    volumes:
      - ${DATA}/3x-ui/db/:/etc/x-ui/
      - ${DATA}/3x-ui/cert/:/root/cert/
    deploy:
      resources:
        limits:
          memory: ${RES_LIMIT_MEM_GFW:-512M}
        reservations:
          memory: ${RES_RESER_MEM_GFW:-128M}
