
# docker network create --driver overlay --attachable cluster
networks:
  default:
    name: ${NETWORK}
    external: true
    
services:


  # 服务端： 海外节点
  gost:
    image: 'gogost/gost:latest'
    restart: ${SRV_RESTART_MODE:-always}
    ports:
      - '${PORT_GOST:-8989}:8989'
    working_dir: /gost
    command:
      - -DD
      - "-L=http://gost:${GOST_TOKEN}@0.0.0.0:8989"
      - "-F=relay+wss://gost:${GOST_TOKEN}@${GOST_SERVER_URL}:8989"
    labels:
      - traefik.enable=true
      - traefik.http.routers.gost.rule=HostRegexp(`^gost\..*`)
      - traefik.http.routers.gost.tls=true
      - traefik.http.routers.gost.entrypoints=websecure
      - traefik.http.routers.gost.service=gost@docker
      - traefik.http.services.gost.loadbalancer.server.port=8989
      - traefik.http.services.gost.loadBalancer.passHostHeader=true
      - traefik.http.middlewares.gost.compress=true
    deploy:
      resources:
        limits:
          memory: ${RES_LIMIT_MEM_GOST:-512M}
        reservations:
          memory: ${RES_RESER_MEM_GOST:-128M}