
# docker network create --driver overlay --attachable cluster
networks:
  default:
    name: ${NETWORK}
    external: true
    

services:

  alist:
    image: 'xhofe/alist:latest'
    # restart: ${SRV_RESTART_MODE:-always}
    volumes:
        - ${DATA}/alist:/opt/alist/data
    ports:
        - '${PORT_ALIST}:5244'
    environment:
        - PUID=0
        - PGID=0
        - UMASK=022
    labels:
      - traefik.enable=true
      - traefik.http.routers.alist.rule=HostRegexp(`^alist\..*`)
      - traefik.http.routers.alist.tls=true
      - traefik.http.routers.alist.entrypoints=websecure
      - traefik.http.routers.alist.service=alist@docker
      - traefik.http.services.alist.loadbalancer.server.port=5244
      - traefik.http.services.alist.loadBalancer.passHostHeader=true
      - traefik.http.middlewares.alist.compress=true
    deploy:
      restart_policy:
        condition: ${SRV_RESTART_MODE:-any}
      replicas: 1
      placement:
        constraints:
          - node.labels.app_alist == true
      resources:
        limits:
          memory: ${RES_LIMIT_MEM_ALIST:-512M}
        reservations:
          memory: ${RES_RESER_MEM_ALIST:-128M}
