
networks:
  default:
    name: ${NETWORK}
    external: true


services:
  cronic:
    image: hectorm/supercronic:latest
    restart: ${SRV_RESTART_MODE:-always}
    volumes:
      - ${DATA}/cronic/crontab:/etc/crontab
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    deploy:
      resources:
        limits:
          memory: ${RES_LIMIT_MEM_SUPERCRONIC:-128M}
        reservations:
          memory: ${RES_RESER_MEM_SUPERCRONIC:-64M}