# docker network create --driver overlay --attachable cluster
networks:
  default:
    name: ${NETWORK}
    external: true

configs:
  prometheus-config:
    name: ${PROMETHEUS_CONFIG}
    external: true
  prometheus-rules:
    name: ${PROMETHEUS_RULES}
    external: true

services:
  prometheus:
    image: prom/prometheus:v3.0.1
    # restart: ${SRV_RESTART_MODE:-always}
    user: "nobody"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=${PROMETHEUS_RETENTION:-30d}'
      - '--storage.tsdb.retention.size=${PROMETHEUS_RETENTION_SIZE:-10GB}'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
      - '--web.enable-remote-write-receiver'
    ports:
      - "${PORT_PROMETHEUS:-9090}:9090"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${TEMP}/prometheus/data:/prometheus
    configs:
      - source: prometheus-config
        target: /etc/prometheus/prometheus.yml
      - source: prometheus-rules
        target: /etc/prometheus/rules/alert-rules.yml
    environment:
      - TZ=Asia/Shanghai
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9090/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    labels:
      - traefik.enable=true
      - traefik.http.routers.prometheus.rule=HostRegexp(`^prometheus\..*`)
      - traefik.http.routers.prometheus.tls=true
      - traefik.http.routers.prometheus.entrypoints=websecure
      - traefik.http.services.prometheus.loadbalancer.server.port=9090
      - traefik.http.middlewares.prometheus.compress=true
   
    deploy:
      restart_policy:
        condition: ${SRV_RESTART_MODE:-any}
      replicas: 1
      placement:
        constraints:
          - node.labels.app_prometheus == true
      resources:
        limits:
          memory: ${RES_LIMIT_MEM_PROMETHEUS:-2G}
        reservations:
          memory: ${RES_RESER_MEM_PROMETHEUS:-512M}
