

networks:
  default:
    name: ${NETWORK}
    external: true


services:
  ghproxy:
    image: hunsh/gh-proxy-py:latest
    restart: ${SRV_RESTART_MODE:-always}
    ports:
      - "${PORT_PROXY_GH}:80"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.ghproxy.rule=HostRegexp(`^gh\..*`)
      - traefik.http.routers.ghproxy.tls=true
      - traefik.http.routers.ghproxy.entrypoints=websecure
      - traefik.http.routers.ghproxy.service=ghproxy@docker
      - traefik.http.services.ghproxy.loadbalancer.server.port=80
      - traefik.http.services.ghproxy.loadBalancer.passHostHeader=true
    deploy:
      resources:
        limits:
          memory: ${RES_LIMIT_MEM_GHPROXY:-512M}
        reservations:
          memory: ${RES_RESER_MEM_GHPROXY:-128M}
