

networks:
  default:
    name: ${NETWORK}
    external: true

services:
  
  gitea:
    image: docker.gitea.com/gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=mysql8:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=root
      - GITEA__database__PASSWD=${PASSWORD}
    # restart: always
    volumes:
      - ${DATA}/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "${PORT_GITEA}:3000"
      - "${PORT_GITEA_SSH}:22"
    deploy:
      replicas: 1
      restart_policy:
        condition: ${SRV_RESTART_MODE:-any}
      placement:
        constraints:
          - node.labels.app_gitea == true
      resources:
        limits:
          memory: ${RES_LIMIT_MEM_GITEA:-512M}
        reservations:
          memory: ${RES_RESER_MEM_GITEA:-128M}
