
# docker network create --driver overlay --attachable cluster
networks:
  default:
    name: ${NETWORK}
    external: true


services:

  redis-ui:
    image: patrikx3/p3x-redis-ui
    hostname: redis-ui
    # restart: ${SRV_RESTART_MODE:-always}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA}/p3x-redis:/settings
    ports:
      - ${PORT_REDIS_UI}:7843
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.redis-ui-auth.basicauth.users=admin:${HTPASSWD}
      - traefik.http.routers.redis-ui.rule=Host(`redis-ui.${DOMAIN}`)
      - traefik.http.routers.redis-ui.tls=true
      - traefik.http.routers.redis-ui.middlewares=redis-ui-auth
      - traefik.http.routers.redis-ui.entrypoints=websecure
      - traefik.http.routers.redis-ui.service=redis-ui@docker
      - traefik.http.services.redis-ui.loadbalancer.server.port=7843
    deploy:
      restart_policy:
        condition: ${SRV_RESTART_MODE:-any}
      replicas: 1
      placement:
        constraints:
          - node.labels.app_redisui == true
      resources:
        limits:
          memory: ${RES_LIMIT_MEM_REDISUI:-512M}
        reservations:
          memory: ${RES_RESER_MEM_REDISUI:-128M}

