

# docker network create --driver overlay --attachable cluster
networks:
  default:
    name: ${NETWORK}
    external: true

services:

  rmqnamesrv:
    image: apache/rocketmq:latest
    container_name: rmqnamesrv
    restart: ${SRV_RESTART_MODE:-always}
    ports:
      - ${PORT_ROCKETMQ_NAMESRV}:9876
    command: sh mqnamesrv
    deploy:
      mode: global
      placement:
        constraints: 
          - node.role == manager
      resources:
        limits:
          memory: ${RES_LIMIT_MEM_RMQNAMESRV:-${RES_LIMIT_MEM:-1G}}
        reservations:
          memory: ${RES_RESER_MEM_RMQNAMESRV:-${RES_RESER_MEM:-64M}}
  rmqbroker:
    image: apache/rocketmq:latest
    container_name: rmqbroker
    restart: ${SRV_RESTART_MODE:-always}
    ports:
      - ${PORT_ROCKETMQ_BROKER}:10909
      - ${PORT_ROCKETMQ_BROKER_HTTP}:10911
      - ${PORT_ROCKETMQ_BROKER_HTTPS}:10912
    environment:
      - NAMESRV_ADDR=rmqnamesrv:9876
    volumes:
      - ${DATA}/rocketmq/store:/home/rocketmq/store
    depends_on:
      - rmqnamesrv
    command: sh mqbroker
    deploy:
      mode: global
      placement:
        constraints: 
          - node.role == manager
      resources:
        limits:
          memory: ${RES_LIMIT_MEM_RMQBROKER:-${RES_LIMIT_MEM:-1G}}
        reservations:
          memory: ${RES_RESER_MEM_RMQBROKER:-${RES_RESER_MEM:-64M}}
          
  rmqproxy:
    image: apache/rocketmq:latest
    container_name: rmqproxy
    restart: ${SRV_RESTART_MODE:-always}
    depends_on:
      - rmqbroker
      - rmqnamesrv
    ports:
      - ${PORT_ROCKETMQ_PROXY_HTTP}:8080
      - ${PORT_ROCKETMQ_PROXY_HTTPS}:8081
    environment:
      - NAMESRV_ADDR=rmqnamesrv:9876
    command: sh mqproxy
    deploy:
      mode: global
      placement:
        constraints: 
          - node.role == manager
      resources:
        limits:
          memory: ${RES_LIMIT_MEM_RMQPROXY:-${RES_LIMIT_MEM:-1G}}
        reservations:
          memory: ${RES_RESER_MEM_RMQPROXY:-${RES_RESER_MEM:-64M}}

  dashboard:
    image: apacherocketmq/rocketmq-dashboard:latest
    container_name: rmqdashboard
    restart: ${SRV_RESTART_MODE:-always}
    depends_on:
      - rmqproxy
    ports:
      # 修改了映射端口号
      - ${PORT_ROCKETMQ_DASHBOARD_HTTP}:8080
    environment:
      - JAVA_OPTS=-Drocketmq.namesrv.addr=rmqnamesrv:9876
    deploy:
      mode: global
      placement:
        constraints: 
          - node.role == manager
      resources:
        limits:
          memory: ${RES_LIMIT_MEM_RMQDASHBOARD:-${RES_LIMIT_MEM:-1G}}
        reservations:
          memory: ${RES_RESER_MEM_RMQDASHBOARD:-${RES_RESER_MEM:-64M}}