

# docker network create --driver overlay --attachable cluster
networks:
  default:
    name: ${NETWORK}
    external: true

services:

  elasticsearch:
    image: bitnami/elasticsearch:latest
    # restart: ${SRV_RESTART_MODE:-always}
    environment:
      - "ELASTICSEARCH_PASSWORD=${PASSWORD}"
    ports:
      - "${PORT_ELASTICSEARCH_HTTP:-9200}:9200"
      - "${PORT_ELASTICSEARCH_TCP:-9300}:9300"
    volumes:
      # - ./config:/usr/share/elasticsearch/config
      - ${DATA}/elasticsearch/data:/usr/share/elasticsearch/data
      - ${DATA}/elasticsearch/plugins:/usr/share/elasticsearch/plugins
    deploy:
      restart_policy:
        condition: ${SRV_RESTART_MODE:-any}
      replicas: 1
      placement:
        constraints:
          - node.labels.app_elasticsearch == true
      resources:
        limits:
          memory: ${RES_LIMIT_MEM_ELASTICSEARCH:-2G}
        reservations:
          memory: ${RES_RESER_MEM_ELASTICSEARCH:-512M}

