

networks:
  default:
    name: ${NETWORK}
    external: true

services:
  nginx:
    # image: nginx:latest
    image: openresty/openresty:alpine
    # restart: ${SRV_RESTART_MODE:-always}
    user: "root"
    ports:
      - "${PORT_PROXY:-80}:80"
      - "${PORT_PROXY_SSL:-443}:443"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      # openresty /usr/local/openresty/nginx/conf/nginx.conf
      # openresty /etc/nginx/conf.d
      # - ${DATA}/nginx:/usr/share/nginx/html
      # - ${DATA}/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # - ${DATA}/nginx/conf:/usr/local/openresty/nginx/conf
      # - ${DATA}/nginx/conf.d:/etc/nginx/conf.d
      # - ${DATA}/nginx/html:/usr/local/openresty/nginx/html
      # - ${DATA}/nginx/logs:/usr/local/openresty/nginx/logs
      # - ${DATA}/nginx/lua:/usr/local/openresty/nginx/lua
    environment:
      - TZ=Asia/Shanghai
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -f http://localhost:80/ || exit 1"]
    #   interval: 30s
    #   timeout: 5s
    #   retries: 3
    #   start_period: 20s
    labels:
      - traefik.enable=true
      - traefik.http.routers.nginx.rule=HostRegexp(`^nginx\..*`)
      - traefik.http.routers.nginx.tls=true
      - traefik.http.routers.nginx.entrypoints=websecure
      - traefik.http.services.nginx.loadbalancer.server.port=80
      - traefik.http.middlewares.nginx.compress=true
    deploy:
      restart_policy:
        condition: ${SRV_RESTART_MODE:-any}
      replicas: 1
      placement:
        constraints:
          - node.labels.app_nginx == true
      resources:
        limits:
          memory: ${RES_LIMIT_MEM_NGINX:-512M}
        reservations:
          memory: ${RES_RESER_MEM_NGINX:-128M}
