
# docker network create --driver overlay --attachable cluster
networks:
  default:
    name: ${NETWORK}
    external: true


services:

  postgresql:
    image: postgres:17
    # restart: ${SRV_RESTART_MODE:-always}
    # privileged: true  # Docker Stack 不支持
    ports:
      - "${PORT_POSTGRESQL}:5432"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA}/postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ${PASSWORD}
    deploy:
      restart_policy:
        condition: ${SRV_RESTART_MODE:-any}
      replicas: 1
      placement:
        constraints:
          - node.labels.app_postgresql == true
      resources:
        limits:
          memory: ${RES_LIMIT_MEM_POSTGRESQL:-2G}
        reservations:
          memory: ${RES_RESER_MEM_POSTGRESQL:-512M}
