

# docker network create --driver overlay --attachable cluster
# 使用 host 网络模式的服务不需要定义 overlay 网络
# networks:
#   default:
#     name: ${NETWORK}
#     external: true

configs:
  frps-config:
    name: ${FRPS_CONFIG}
    external: true

services:

  frps:
    image: snowdreamtech/frps:0.65.0-alpine
    # restart: ${SRV_RESTART_MODE:-always}
    volumes:
      - /etc/localtime:/etc/localtime:ro
    configs:
      - source: frps-config
        target: /etc/frp/frps.toml
    labels:
      - traefik.enable=true
      # - traefik.http.routers.frps-http.rule=HostRegexp(`^frp-.+\..*`)
      # - traefik.http.routers.frps-http.tls=true
      # - traefik.http.routers.frps-http.entrypoints=websecure
      # - traefik.http.routers.frps-http.service=frps-http@docker
      # - traefik.http.services.frps-http.loadbalancer.server.port=8080
      # - traefik.http.services.frps-http.loadBalancer.passHostHeader=true
      # - traefik.http.middlewares.frps-http.headers.customrequestheaders.X-Forwarded-Proto=https
      # - traefik.http.middlewares.frps-http.headers.contentSecurityPolicy=upgrade-insecure-requests
      # - traefik.tcp.routers.frps-tcp.rule=HostSNIRegexp(`^tcp-.+\..*`)
      # - traefik.tcp.routers.frps-tcp.tls=true
      # - traefik.tcp.routers.frps-tcp.entrypoints=websecure
      # - traefik.tcp.routers.frps-tcp.service=frps-tcp@docker 
      # - traefik.tcp.services.frps-tcp.loadbalancer.server.port=8000
      - traefik.http.routers.frps-ui.rule=HostRegexp(`^frps\..*`)
      - traefik.http.routers.frps-ui.tls=true
      - traefik.http.routers.frps-ui.entrypoints=websecure
      - traefik.http.routers.frps-ui.service=frps-ui@docker
      - traefik.http.services.frps-ui.loadbalancer.server.port=${PORT_FRPS_UI:-7500}
    # healthcheck:
    #   test: ["CMD-SHELL", "pgrep frps || exit 1"]
    #   interval: 30s
    #   timeout: 5s
    #   retries: 3
    #   start_period: 15s
    deploy:
      restart_policy:
        condition: ${SRV_RESTART_MODE:-any}
      replicas: 1
      placement:
        constraints:
          - node.labels.app_frps == true
      resources:
        limits:
          memory: ${RES_LIMIT_MEM_FRPS:-256M}
        reservations:
          memory: ${RES_RESER_MEM_FRPS:-64M}
    ports:
      - {target: 7000, published: 7000, mode: host}
      - {target: 7500, published: 7500, mode: host}



