
# docker network create --driver overlay --attachable cluster
networks:
  default:
    name: ${NETWORK}
    external: true


services:

  portainer:
    image: portainer/portainer-ce:latest
    hostname: portainer
    restart: ${SRV_RESTART_MODE:-always}
    ports:
      - "${PORT_PORTAINER}:9000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DATA}/portainer/data:/data
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.portainer-auth.basicauth.users=admin:${HTPASSWD}
      - traefik.http.routers.portainer.rule=Host(`portainer.${DOMAIN}`)
      - traefik.http.routers.portainer.tls=true
      - traefik.http.routers.portainer.middlewares=portainer-auth
      - traefik.http.routers.portainer.entrypoints=websecure
      - traefik.http.routers.portainer.service=portainer@docker
      - traefik.http.services.portainer.loadbalancer.server.port=9000
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          memory: ${RES_LIMIT_MEM_PORTAINER:-${RES_LIMIT_MEM:-1G}}
        reservations:
          memory: ${RES_RESER_MEM_PORTAINER:-${RES_RESER_MEM:-64M}}
