
# docker network create --driver overlay --attachable cluster
networks:
  default:
    name: ${NETWORK}
    external: true

configs:
  mysql8-config:
    name: ${MYSQL8_CONFIG}
    external: true

services:

  mysql8:
    image: mysql:8.0-oracle
    # restart: ${SRV_RESTART_MODE:-always}
    # privileged: true  # Docker Stack 不支持
    ports:
      - "${PORT_MYSQL8}:3306"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA}/mysql8/data:/var/lib/mysql
      - ${DATA}/mysql8/log:/var/log/mysql
    configs:
      - source: mysql8-config
        target: /etc/mysql/my.cnf
    environment:
      TIMEZONE: Asis/Shanghai
      MYSQL_ROOT_PASSWORD: ${PASSWORD}
      MYSQL_DATABASE: public
    command:
      --innodb-flush-method=fsync
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    labels:
      - "logging.enabled=true"
      - "app_name=mysql8"
      - "environment=${ENV}"
      - "logging_level=INFO"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    deploy:
      restart_policy:
        condition: ${SRV_RESTART_MODE:-any}
      replicas: 1
      placement:
        constraints:
          - node.labels.app_mysql8 == true
      resources:
        limits:
          memory: ${RES_LIMIT_MEM_MYSQL8:-2G}
        reservations:
          memory: ${RES_RESER_MEM_MYSQL8:-512M}
