
# docker network create --driver overlay --attachable cluster
networks:
  default:
    name: ${NETWORK}
    external: true

services:

  redis:
    image: redis:7
    # restart: ${SRV_RESTART_MODE:-always}
    ports:
      - "${PORT_REDIS}:6379"
    environment:
      - PASSWORD=${PASSWORD:-}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA}/redis:/data
    command: 
      - redis-server 
      - '--requirepass "${PASSWORD:-}"'
      - '--tcp-keepalive 50'
      - '--appendonly yes'
      - '--appendfsync everysec'
      #- '--stop-writes-on-bgsave-error no'
      - '--save 60 1'
      - '--bind 0.0.0.0'
      - '--protected-mode yes'
    healthcheck:
      test: ["CMD-SHELL", "redis-cli --no-auth-warning -a \"${PASSWORD:-}\" ping | grep -q PONG"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    deploy:
      restart_policy:
        condition: ${SRV_RESTART_MODE:-any}
      replicas: 1
      placement:
        constraints:
          - node.labels.app_redis == true
      resources:
        limits:
          memory: ${RES_LIMIT_MEM_REDIS:-1G}
        reservations:
          memory: ${RES_RESER_MEM_REDIS:-256M}

